"""XLSX matrix export via openpyxl. Every cell is written as a string: nothing is ever interpreted as a formula."""

import io
import re

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from rvs_core import textcheck
from rvs_core.exporters.zipnorm import normalize_zip
from rvs_core.matrices.provenance import Provenance
from rvs_core.matrices.table import MatrixTable

_GAP_FILL = {"unverified-approved": "FFD7D9", "orphan": "FFD7D9", "unverified": "FCF4D6", "childless": "FCF4D6"}


XLSX_CELL_LIMIT = 32_767  # characters an Excel cell can hold; openpyxl silently cuts longer strings


def set_text(cell, value: str) -> None:  # type: ignore[no-untyped-def]
    """Store ``value`` as a string even when it starts with '=', '+', '-' or '@'.

    Characters XML cannot hold are replaced and over-long text is cut with a visible marker (an exact copy of the data is
    the CSV/ReqIF export; the items XLSX export refuses long cells before it gets here)."""
    if value == "":
        return
    value = textcheck.clean(value)
    if len(value) > XLSX_CELL_LIMIT:
        value = value[: XLSX_CELL_LIMIT - 20] + " … [text cut]"
    cell.value = value
    cell.data_type = "s"


def style_header(ws, ncols: int) -> None:  # type: ignore[no-untyped-def]
    for c in range(1, ncols + 1):
        cell = ws.cell(row=1, column=c)
        cell.font = Font(bold=True)
        cell.fill = PatternFill("solid", fgColor="F4F4F4")
        cell.alignment = Alignment(vertical="top")
    ws.freeze_panes = "A2"
    if ws.max_row >= 1 and ncols:
        ws.auto_filter.ref = f"A1:{get_column_letter(ncols)}{max(ws.max_row, 1)}"


def fit_columns(ws, columns: list[str], rows: list[list[str]]) -> None:  # type: ignore[no-untyped-def]
    for i, name in enumerate(columns, start=1):
        longest = max([len(name)] + [len(max(r[i - 1].splitlines() or [""], key=len)) for r in rows[:500]])
        ws.column_dimensions[get_column_letter(i)].width = min(max(longest + 2, 8), 60)


def provenance_sheet(wb: Workbook, prov: Provenance, notes: tuple[str, ...] = ()) -> None:
    ws = wb.create_sheet("Provenance")
    rows = [("Project", prov.project), ("Baseline", prov.baseline), ("Generated", prov.generated.strftime("%Y-%m-%d %H:%M:%S")),
            ("Generated by", prov.user), ("Tool", f"rvs {prov.tool_version}"), ("Framework", f"doorstop {prov.framework_version}")]  # fmt: skip
    rows += [("Note", n) for n in notes]
    for r, (k, v) in enumerate(rows, start=1):
        ws.cell(row=r, column=1, value=k).font = Font(bold=True)
        set_text(ws.cell(row=r, column=2), v)
    ws.column_dimensions["A"].width = 16
    ws.column_dimensions["B"].width = 70


def finish(wb: Workbook, prov: Provenance, title: str) -> bytes:
    wb.properties.creator = prov.user
    wb.properties.lastModifiedBy = prov.user
    wb.properties.title = title
    wb.properties.created = wb.properties.modified = prov.generated
    buf = io.BytesIO()
    wb.save(buf)
    stamp = prov.generated.strftime("%Y-%m-%dT%H:%M:%SZ").encode()
    # openpyxl stamps "modified" with the save time; pin it to the provenance date so output is reproducible
    return normalize_zip(
        buf.getvalue(),
        {"docProps/core.xml": lambda b: re.sub(rb"(<dcterms:(?:modified|created)[^>]*>)[^<]*", rb"\g<1>" + stamp, b)},
    )


def render_xlsx(table: MatrixTable) -> bytes:
    wb = Workbook()
    ws = wb.active
    assert ws is not None
    ws.title = "Matrix"
    for c, name in enumerate(table.columns, start=1):
        ws.cell(row=1, column=c, value=name)
    wrap = Alignment(vertical="top", wrap_text=True)
    fills = {k: PatternFill("solid", fgColor=v) for k, v in _GAP_FILL.items()}
    for r, row in enumerate(table.rows, start=2):
        flag = table.flags[r - 2] if r - 2 < len(table.flags) else None
        for c, value in enumerate(row, start=1):
            cell = ws.cell(row=r, column=c)
            set_text(cell, value)
            cell.alignment = wrap
            if flag:
                cell.fill = fills.get(flag) or PatternFill("solid", fgColor="FCF4D6")
    style_header(ws, len(table.columns))
    fit_columns(ws, table.columns, table.rows)
    provenance_sheet(wb, table.provenance, table.notes)
    return finish(wb, table.provenance, table.title)
